<div class="page-title">
    <h1><?php echo $this->__('My Gift Certificates') ?></h1>
</div>
<form name="giftcardForm" action="<?php echo $this->getUrl('customer/giftcards/balance') ?>" method="post">
	<div class="row">
		<h2 class="span12" style="margin-bottom:20px;"><?php echo $this->__('Check Gift Certificate Balance') ?></h2>
		<label class="span3"><?php echo $this->__('Enter the Gift Certificate') ?>:</label>
		<div class="span3">
			<input type="text" class="input-text" id="giftcard_code" name="giftcard_code" value=""/>
		</div>
	</div>
	<div class="row">
		<?php if(($aResult = $this->getCurrentBalance()) !== false): ?>
			<div class="alert alert-success span6" style="margin-top:20px;">
				<?php echo 'Gift Card: "'.$aResult['card_code'].'" '.Mage::helper('core')->currency($aResult['card_balance']); ?>
			</div>
		<?php endif;?>
	</div>
	<div class="row">
		<div class="span3" style="margin-top:20px;">
			<button type="button" title="<?php echo $this->__('Check') ?>" class="button btn btn-lrg btn-primary" onclick="document.forms['giftcardForm'].submit()" value="<?php echo $this->__('Redeem') ?>"><?php echo $this->__('Check') ?></button>
		</div>
	</div>
</form>