<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<div class="discount">
    <h2><?php echo $this->__('Gift Certificate'); ?></h2>
</div>
<form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard" class="form-inline">
    <div class="control-group row">
    	<label class="control-label span2" for="giftcard_code"><?php echo $this->__('Card Number') ?></label> 
    	<div class="controls span3">
			<input value="" type="text" name="giftcard_code" id="giftcard_code" class="input-text">
		</div>
		<button type="submit" class="btn green-btn" title="<?php echo $this->__('Add') ?>" onclick="giftCardForm.submit(true)"><span><?php echo $this->__('Redeem') ?></span></button>
	    <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
	    <div class="span5" style="margin-top:5px;">
	    	<?php if($oGiftCardSession->getActive())
	            foreach($oGiftCardSession->getFrontOptions() as $k => $v)
	            {
	                if($temp) {
	                    echo '<br/><br/>';
	                }
	                echo '<p><b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' **********'.$v['code'].'.</b></p>';
	                echo '<p>'.$this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="'.$this->getUrl("giftcards/cart/deActivateGiftCard/id/$k").'">'.$this->__('Remove').'</a>)</p>';
	                $temp = 1;
	            }
		    ?>
	    </div>
	</div>
</form>
<script type="text/javascript">
    //&lt;![CDATA[
    var deActivateGiftCardForm = new VarienForm('deActivateGiftCard');
    var giftCardForm = new VarienForm('activateGiftCard');
    //]]&gt;
</script>
