<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<div class="discount">
    <h2><?php echo $this->__('Gift Certificate'); ?></h2>
</div>
<form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard" class="form-inline">
    <div class="control-group row">
    	<label class="control-label span2" for="giftcard_code"><?php echo $this->__('Card Number') ?></label> 
    	<div class="controls span3">
			<input value="" type="text" name="giftcard_code" id="giftcard_code" class="input-text">
		</div>
		<button type="submit" title="<?php echo $this->__('Activate') ?>" onclick="giftCardForm.submit(true)" value="<?php echo $this->__('Activate') ?>"></button>
	    <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
	    <?php if($oGiftCardSession->getActive())
            foreach($oGiftCardSession->getFrontOptions() as $k => $v)
            {
                if($temp) {
                    echo '<br/><br/>';
                }
                echo '<b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="'.$this->getUrl("giftcards/cart/deActivateGiftCard/id/$k").'">'.$this->__('Remove').'</a>)';
                $temp = 1;
            }
	    ?>
	</div>
</form>
<script type="text/javascript">
    //&lt;![CDATA[
    var deActivateGiftCardForm = new VarienForm('deActivateGiftCard');
    var giftCardForm = new VarienForm('activateGiftCard');
    //]]&gt;
</script>
