<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="welcome-msg">
    <p class="hello"><strong><?php echo $this->__('Welcome, %s', $this->htmlEscape($this->getCustomerName())) ?></strong></p>
    <p><?php echo $this->__('Your Dashboard allows you to view a snapshot of your recent account activity or update your account information. Select a link below to get started.') ?></p>
</div>
