<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
$cart = Mage::getModel('checkout/cart')->getQuote();
$shippingMethod = $cart->getShippingAddress();
?>
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
			<div class="cart-row" style="margin-top:50px;">
				<div class="row">
					<div class="span5">
						<h6>Product</h6>
					</div>
					<div class="span3">
						<h6>Quantity</h6>
					</div>
					<div class="span2">
						<h6>Price</h6>
					</div>
					<div class="span2">
						<h6>Total</h6>
					</div>
				</div>
			</div>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
		<div class="cart-row confirm-row">
	        <?php $session = Mage::getSingleton('checkout/session');?>
			<?php foreach($session->getQuote()->getAllItems() as $item): ?>
	            <div class="row" style="<?php if (!$item->getParentItemId()): ?>margin-bottom:10px; margin-top:10px;<?php endif;?>">
					<div id="review-product-info" class="span5">
						<?php if(!$item->getParentItemId()):?>
							<?php echo $this->getItemHtml($item)?>
						<?php endif;?>	
					</div>
					<div class="span3">
						<?php if (!$item->getParentItemId()): ?>
							<p><?php echo round($item->getQty(), 0); ?></p>
						<?php endif; ?>
					</div>
					<div class="span2">
						<?php if (!$item->getParentItemId()): ?>
							<p><?php echo Mage::helper("core")->currency($item->getPrice()); ?></p>
						<?php endif; ?>
					</div>
					<div class="span2">
						<?php if (!$item->getParentItemId()): ?>
							<p><?php echo Mage::helper("core")->currency($item->getPrice() * $item->getQty()); ?></p>
						<?php endif; ?>
					</div>
				</div>
	        <?php endforeach ?>
        </div>
        <div class="cart-row totals-row">
			<div class="row 1">
				<div class="span2 offset8">
					<h6>Subtotal</h6>
				</div>
				<div class="span2">
					<p><?php echo Mage::helper("core")->currency($cart['subtotal']); ?></p>
				</div>
			</div>
			<div class="row 2">
				<div class="span2 offset8">
					<h6>Shipping</h6>
				</div>
				<div class="span2">
					<p><?php echo Mage::helper('core')->currency($shippingMethod['shipping_amount'],true,false); ?></p>
				</div>
			</div>
			<div class="row 2">
				<div class="span2 offset8">
					<h6>Tax</h6>
				</div>
				<div class="span2">
					<p><?php echo Mage::helper("core")->currency($cart['tax_amount']); ?></p>
				</div>
			</div>
			<div class="row 3">
				<div class="span2 offset8">
					<h6>Total</h6>
				</div>
				<div class="span2">
					<p><?php echo Mage::helper("core")->currency($cart['grand_total']); ?></p>
					<p style="display:none;">Discount Amount: <?php echo Mage::helper("core")->currency($cart['subtotal'] - $cart['subtotal_with_discount']); ?> Code: <?php echo $cart['coupon_code']; ?></p>
				</div>
			</div>
		</div>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
	_gaq.push(['trackPageview','/checkout/order-review/']);
	ga('send', 'pageview', '/checkout/order-review/');
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit" class="row">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set span3 offset9" id="review-buttons-container">
        <a style="margin-bottom:10px;" class="btn btn-lrg" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a>
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
