<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php $_item = $this->getItem()?>
<p class="product-name"><?php echo $this->htmlEscape($this->getProductName()) ?></p>
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
<?php 
$session = Mage::getSingleton('checkout/session');
$attributes = null;
foreach ($session->getQuote()->getAllItems() as $item)
{
	$options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
	if(isset($options['attributes_info']))
	{
		$attributes = $options['attributes_info'];
	}
}

$product = $_item->getProduct();
$selectionCollection = $product->getTypeInstance(true)->getSelectionsCollection($product->getTypeInstance(true)->getOptionsIds($product), $product);

foreach($selectionCollection as $option)
{ ?>        
   	<dt></dt>	   	
    <?php if($option->getTypeId() == 'configurable'):?>
	    <?php foreach($attributes as $attribute){
			if($attribute['label'] == 'Size')
			{
				$sizeDisplay = 'Size '.$attribute['value'];
			}
			if($attribute['label'] == 'Base Color')
			{
				$baseDisplay = $attribute['value'].' Base';
			}
		}?>
    	<dd><?php echo $baseDisplay.' - '.$sizeDisplay ?></dd>
    <?php else:?>
    	<dd><?php echo $option->getName() ?></dd>
    <?php endif;?>
<?php }?>	
</dl>
<?php endif;?>