<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php $_item = $this->getItem()?>
<p class="product-name"><?php echo $this->htmlEscape($this->getProductName()) ?></p>
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
<?php 														 
	if($_children = $_item->getChildren())
	{
		foreach($_children as $child)
		{
			if($child->getProductType() == 'configurable')
			{
				//The Product Id of the Simple Product
		        $optionId = $child->getOptionByCode('simple_product')->getProductId();
		
		        //The Simple Product
		        $configurableOption = Mage::getModel('catalog/product')->load($optionId);
				$size = $configurableOption->getAttributeText('size');
				$baseColor = $configurableOption->getAttributeText('base_color');
				if(!empty($size) || !empty($baseColor)){?>
				<dd><?php echo 'Size '.$size.' - '.$baseColor.' Base' ?></dd>
				<?php }?>
			<?php }	
			else
			{?>
				<dd><?php echo $child->getName() ?></dd>
			<?php }									
		}
	}
?>							
</dl>
<?php endif;?>