<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="product-options span5" id="product-options-wrapper">
    <?php echo $this->getChildHtml('', true, true);?>
    <!--<?php if ($this->hasRequiredOptions()):?>
        <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
    <?php endif;?>-->
    <div id="extra-links">
		<a id="returns" href="#">Free Shipping & Returns</a>
		<a href="https://secure.livechatinc.com/licence/1311232/open_chat.cgi?groups=0" onclick="return !window.open(this.href, 'Live Chat', 'width=500,height=500')" target="_blank">LIVE CHAT</a>
		<a id="shipping" href="#">Shipping Rates</a>
	</div>
</div>
