<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
    <div class="discount">
        <h2><?php echo $this->__('Promotion') ?></h2>
    </div>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post" class="form-inline">
	<div class="control-group row">
		<label class="control-label span2" for="coupon_code"><?php echo $this->__('Promotion Code') ?></label>
		<div class="controls span3">
			<input type="hidden" name="remove" id="remove-coupone" value="0" />
            <input class="input-text" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
		</div>
		<button type="submit" title="<?php echo $this->__('Apply Coupon') ?>" class="btn green-btn" onclick="discountForm.submit(false)" ><span><?php echo $this->__('Apply') ?></span></button>
		<?php if(strlen($this->getCouponCode())): ?>
			<div class="span5" style="margin-top:5px;">
				<a title="<?php echo $this->__('Remove Coupon') ?>" onclick="discountForm.submit(true)" value="<?php echo $this->__('Remove Coupon') ?>"><?php echo $this->__('Remove Coupon') ?></a>
			</div>
		<?php endif;?>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
