<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * @see Mage_Checkout_Block_Cart_Shipping
 */
?>
<div class="shipping">
    <h2><?php echo $this->__('Shipping') ?></h2>
    <div class="shipping-form">
       <form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-zip-form" class="form">
           <fieldset>
                <div class="control-group row">
                    <label class="control-label span2" for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="controls span3">
                        <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
                    </div>
                </div>
            <?php //if($this->getStateActive()): ?>
                <div class="control-group row">
                    <label class="control-label span2" for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"' ?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>' ?><?php echo $this->__('State/Province') ?></label>
                    <div class="controls span3">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
                            <option value=""><?php echo $this->__('SELECT STATE') ?></option>
                        </select>
                       <script type="text/javascript">
                       //<![CDATA[
                           $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
                       //]]>
                       </script>
                       <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getEstimateRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                   </div>
                </div>
            <?php //endif; ?>
            <?php if($this->getCityActive()): ?>
                <div class="control-group row">
                    <label class="control-label span2" for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
                    <div class="controls span3">
                        <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
                    </div>
                </div>
            <?php endif; ?>
                <div class="control-group row">
                    <label class="control-label span2" for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="controls span3">
                        <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
                    </div>
                </div>
               <button type="button" title="<?php echo $this->__('Get a Quote') ?>" onclick="coShippingMethodForm.submit()" class="btn btn-lrg"><span><span><?php echo $this->__('Get a Quote') ?></span></span></button>
            </fieldset>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
        //]]>
        </script>

        <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        <form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>" class="form" style="margin-top:30px">

            
                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                    <div class="control-group row">
	                    <label class="control-label span2">Shipping Method</label>
	                    <div class="controls span3">
	                    	<select id="estimate_method" name="estimate_method">   
	                    		<option value="">Select</option>                 	
	                        <?php foreach ($_rates as $_rate): ?>
	                           	<?php if ($_rate->getErrorMessage()): ?>
	                                <?php echo $_rate->getErrorMessage() ?>
	                           	<?php else: ?>                               	
	                           	<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
	                           	<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
	                           	<option value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' selected="selected"' ?>><?php echo $_rate->getMethodTitle() ?> <?php echo $_excl; ?><?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)<?php endif; ?></option>
	                                <!--div class="controls">
	                                <label for="s_method_<?php echo $_rate->getCode() ?>" class="radio">
	                                    <?php echo $_rate->getMethodTitle() ?>
	                                    <input name="estimate_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
	                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
	                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
	                                    <?php echo $_excl; ?><?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)<?php endif; ?>
	                                </label>
	                                </div-->
	                           <?php endif ?>
	                        <?php endforeach; ?>
	                        </select>
	                     </div>
                     </div> 
                <?php endforeach; ?>
                                                      
			<button type="submit" title="<?php echo $this->__('Update Total') ?>" class="btn btn-lrg" name="do" value="<?php echo $this->__('Update Total') ?>"><span><span><?php echo $this->__('Update Total') ?></span></span></button>
                            
        </form>
        <?php endif; ?>
        <script type="text/javascript">
        //<![CDATA[
            var coShippingMethodForm = new VarienForm('shipping-zip-form');
            var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

            coShippingMethodForm.submit = function () {
                var country = $F('country');
                var optionalZip = false;

                for (i=0; i < countriesWithOptionalZip.length; i++) {
                    if (countriesWithOptionalZip[i] == country) {
                        optionalZip = true;
                    }
                }
                if (optionalZip) {
                    $('postcode').removeClassName('required-entry');
                }
                else {
                    $('postcode').addClassName('required-entry');
                }
                return VarienForm.prototype.submit.bind(coShippingMethodForm)();
            }
        //]]>
        </script>
    </div>
</div>
