<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
<div class="row price-box">
	<div class="span2">
		<h6>Subtotal</h6>
	</div>
	<div class="span2">
		<?php echo $this->renderTotals(); ?>
	</div>
</div>
<div class="row price-box">
	<div class="span2">
		<h6>Shipping</h6>
	</div>
	<div class="span2">
		<div class="price">$0.00</div>
	</div>
</div>
<div class="row price-box" style="margin-bottom:30px;">
	<div class="span2">
		<h6>Estimated Total</h6>
	</div>
	<div class="span2">
		<?php echo $this->renderTotals('footer'); ?>
	</div>
</div>
<button id="displayedUpdate" type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="btn btn-lrg shrink-wrap"><span><span><?php echo $this->__('Update Shopping Cart') ?></span></span></button>
<?php endif; ?>
