<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<div class="col2-set row">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="span5">   
    	<h2><?php echo $this->__('Returning Customers') ?></h2>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" class="form-vertical">
	        <fieldset>
	        	<div class="control-group row">
	            	<label for="email" class="control-label span2"><?php echo $this->__('Email Address') ?></label>
	            	<div class="controls span3">
	                	<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
	            	</div>
				</div>
				<div class="control-group row">    
					<label for="pass" class="control-label span2" style="margin-bottom:0; margin-top:5px;line-height:18px;"><?php echo $this->__('Password') ?></label>
					<div class="controls span3">
						<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
					</div>
					<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forgot-left span2"><?php echo $this->__('Forgot Password?') ?></a>
				</div>
				<?php echo $this->getChildHtml('persistent.remember.me'); ?>
				<?php echo $this->getChildHtml('form.additional.info'); ?>
	            <input name="context" type="hidden" value="checkout" />
	            <div class="row">
					<div class="span3 offset2">
						<button type="submit" class="button btn btn-primary btn-lrg progress-trigger" onclick="onepageLogin(this)"><?php echo $this->__('Sign in & Checkout') ?></button>
					</div>
				</div>
	        </fieldset>
        </form>            
    </div>
    
    <div class="span4 offset1">
        <h2><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Register or Guest Checkout') ?><?php else: ?><?php echo $this->__('Register for Sseko') ?><?php endif; ?></h2>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p style="margin-bottom:40px;"><?php echo $this->__('Continue checkout as a Sseko guest or register for an account. This will give you access to purchase history, shipping status and keep you up to date on Sseko.') ?></p>
        <?php else: ?>
            <p style="margin-bottom:40px;"><?php echo $this->__('Continue checkout as a Sseko guest or register for an account. This will give you access to purchase history, shipping status and keep you up to date on Sseko.') ?></p>
        <?php endif; ?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
            	<li class="span3">
            		<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
	            	<label class="radio" for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                	<li class="span3">
                		<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /> 
	                    <label class="radio" for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>   
                	</li>
                <?php endif; ?>        
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
            
        <div class="buttons-set">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button btn btn-primary btn-lrg progress-trigger" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button btn btn-primary btn-lrg progress-trigger"><span><span><?php echo $this->__('Register') ?></span></span></button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
