<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<script type="text/javascript">
    $.noConflict();
    jQuery(document).ready(function($) {
        // Code that uses jQuery's $ can follow here.
        $('.nav-collapse').on('hidden', function () {
            $('.nav-collapse').show();
        })
        $('#displayedUpdate').click(function(){
        	$('#updateShoppingCart').trigger('click');
        });
        (function($){
	        $.fn.imgSlider = function( options ){
	
	            o = $.extend({
	                next: '.next-button',
	                prev: '.previous-button'
	            }, options);
	            
				$( o.prev ).hide();
	            $( o.next ).hide();
	            var thisCallback = this;
	
	            $( this ).find( 'img' ).each(function(){
	
	                $( this ).hide();
	            });
	            $( this ).find( 'img' ).first().addClass( 'active' ).show();	            
	            var nextImg = $( thisCallback ).find( '.active' ).next();
	            if(nextImg.length != 0)
	            {
	            	$(o.next).show();
	            }	            
	
	            // binding event next
	            $( o.next ).bind( 'click' ,function(){
	
	                nextImg = $( thisCallback ).find( '.active' ).next();
	                if ( nextImg.length == 0 ) {
	
	                    return false;
	                }
	                $( o.prev ).show();
	                $( thisCallback ).find( 'img' ).removeClass( 'active' ).hide();
	                nextImg.addClass( 'active' ).show();
	                if ( nextImg.next().length == 0 ) {
	
	                    $( this ).hide();
	                }
	            });
	            // binding event prev
	            $( o.prev ).bind( 'click' ,function(){
	
	                var prevImg = $( thisCallback ).find( '.active' ).prev();
	                if ( prevImg.length == 0 ) {
	
	                    return false;
	                }
	                $( o.next ).show();
	                $( thisCallback ).find( 'img' ).removeClass( 'active' ).hide();
	                prevImg.addClass( 'active' ).show();
	                if ( prevImg.prev().length == 0 ) {
	
	                    $( this ).hide();
	                }
	            });
	        }
	    })(jQuery);
	    $(document).ready(function() {
		    $('.img-wrap').imgSlider();
		});
		
		$('#returns').click(function(event){
			event.preventDefault();
			open_overlay('returns-overlay', 'pdp-hider');
		});
		$('#shipping').click(function(event){
			event.preventDefault();
			open_overlay('shipping-overlay', 'pdp-hider');
		});
		$('#play-video').click(function(event){
			event.preventDefault();
			open_overlay('video-overlay', 'pdp-hider');
		});
		$('.close-popap').click(function(event){
			event.preventDefault();
			if($(this).attr('id') == 'close-video')
			{
				var embedDiv = $('#video-embed').clone();
				console.log(embedDiv);
				$('#video-embed').remove();
				$('#video-main').append(embedDiv);
			}
			close_overlay();
		});
		$('.quickviewpro-hider').click(function(event){
			event.preventDefault();
			close_overlay();
		});
		function open_overlay(overlayId, hiderId)
		{
			var heightBody = document.getElementsByTagName('body')[0].clientHeight;
			$('#' + hiderId).css('height', heightBody + 'px');
            $('#' + hiderId).show();
            var scrollPos = null;
            if (document.documentElement && document.documentElement.scrollTop) { // Explorer 6 Strict
        		scrollPos = {scrollTop:document.documentElement.scrollTop,scrollLeft:document.documentElement.scrollLeft};
	    	} else if (document.body) {// all other Explorers
	       	 	scrollPos = {scrollTop:document.body.scrollTop,scrollLeft:document.body.scrollLeft};
    		}
            var topPos    = parseInt(0.1 * document.documentElement.clientHeight + scrollPos['scrollTop']);
	
	        $('#' + overlayId).css('top', topPos + 'px');
	        if (window.outerWidth < parseInt($('#' + overlayId).css('width'))) {
	            $('#' + overlayId).css({'left': '0px', 'margin': '0 0 0 20px'});
	        } else {
	            $('#' + overlayId).css({'left': '', 'margin': ''});
	        }
	        $('#' + overlayId).show();			
		}
		function close_overlay()
		{
			$('.quickviewpro-hider').hide();
        	$('.quickviewpro-popup').hide();
		}
		$('.progress-trigger').click(function(event){
			$('.progtrckr li').removeClass( 'progtrckr-active');
			$('.progtrckr li').addClass( 'progtrckr-not');
			$('#progress2').addClass( 'progtrckr-active');
			$('#progress2').removeClass( 'progtrckr-not');
		});
		$('.progress-trigger2').click(function(event){
			$('.progtrckr li').removeClass( 'progtrckr-active');
			$('.progtrckr li').addClass( 'progtrckr-not');
			$('#progress3').addClass( 'progtrckr-active');
			$('#progress3').removeClass( 'progtrckr-not');
		});
		if (($('#order-complete').length == 0) && ($('#shopping-cart-page').length == 0)){
			if ($('#opc-login').length == 0){
				$('.progtrckr li').removeClass( 'progtrckr-active');
				$('.progtrckr li').addClass( 'progtrckr-not');
				$('#progress2').addClass( 'progtrckr-active');
				$('#progress2').removeClass( 'progtrckr-not');
			}
		}
    });
    // Code that uses other library's $ can follow here.
</script>