<?php
$_option = $this->getOption();
$_selections = $_option->getSelections();
//pr(get_class($_option));
$_default = $_option->getDefaultSelection();
$_showSingle = (count($_selections) == 1 && $_option->getRequired());

$totalItems = count($_selections);
?>
<label class="left"><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<span class="required">&nbsp;*</span>' ?></label>
<span class="qty-holder">
    <?php if ($_default): ?>
    <?php $_defaultQty = $_default->getSelectionQty()*1 ?>
    <?php $_canChangeQty = $_default->getSelectionCanChangeQty() ?>
    <?php else: ?>
    <?php if (!$_showSingle): ?>
        <?php $_defaultQty = '0' ?>
        <?php $_canChangeQty = false ?>
        <?php else: ?>
        <?php $_defaultQty = $_selections[0]->getSelectionQty()*1 ?>
        <?php $_canChangeQty = $_selections[0]->getSelectionCanChangeQty() ?>
        <?php endif; ?>
    <?php endif; ?>
    <input onblur="bundle.changeOptionQty(this, event)" <?php echo $_canChangeQty?'':'disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php echo $_canChangeQty?'':' qty-disabled' ?>" type="hidden" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>" />
</span>
<div<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <?php $bundledProds = Array(); ?>
    <?php $simpleProds = array(); ?>
    <?php $simpleProdIds = array(); ?>
    <?php $confItems = array(); ?>
    <?php $confItemIds = array(); ?>
    <?php $confItemOptions = array(); ?>
    <?php

    $removeSimpleProd = false;
    foreach($_selections as $_selection){
        $p = Mage::getModel('catalog/product')->load($_selection->getProductId());
        $_selection->setData('product', $p);
        $type = $p->getTypeId(); #Get Type like configurable or simple.
        if($totalItems > 1 && $type == 'configurable'){
            $removeSimpleProd = true;
        }
    }

    foreach($_selections as $_selection): $p = $_selection->getData('product');
        ?>
        <?php
        $type = $p->getTypeId(); #Get Type like configurable or simple.
        if($removeSimpleProd && $type != 'configurable') {
            $simpleProds[] = $p;
            $simpleProdIds[] = $p->getId();
            continue;
        }

        $customOptions = $p->getProductOptionsCollection();
        if ($customOptions->getItems()) {
            $bundledProds[] = $p;
        }
        $firstChildProduct = $p;
        if($p->getTypeId() == "configurable") {
			$configurableProduct = $p;
            $firstChildProduct = current($p->getTypeInstance()->getUsedProducts());
            if(empty($firstChildProduct)) {
                $firstChildProduct = $p;
            }
        }
        ?>             
        <div class="options">
            <input style="display:none;" onclick="bundle.changeSelection(this)" class="radio<?php echo $_option->getRequired()?' validate-one-required-by-name':'' ?>" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" type="radio" name="bundle_option[<?php echo $_option->getId() ?>]"<?php echo ($_selection->getIsDefault() && $_selection->isSaleable())?' checked="checked" ':'' ?><?php echo !$_selection->isSaleable()?' disabled="disabled" ':'' ?> value="<?php echo $_selection->getSelectionId() ?>" />
            <label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><?php echo $this->getSelectionTitlePrice($_selection) ?></label>
            <?php if($_option->getRequired()): ?>
            <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container'); ?>
            <?php endif; ?>
            <div id="sizeButtons-<?php echo $p->getId() ?>"></div>
        </div>           
        <?php endforeach; ?>
    <span id="bundle-option-<?php echo $_option->getId() ?>-container"></span>
</div>
<script type="text/javascript">
    Event.observe(window, 'load', function(){
        $$('input.radio').each(function(el){
            if(typeof(bundle) == 'undefined') {
                bundle = __bundle;
            }

            if(typeof(bundle) != 'undefined') {
                var name = el.name;
		    	if(name.substring(0, 7) != 'ratings')
		    	{
	                bundle.changeSelection(el);
	                el.writeAttribute('checked', 'checked');
	                el.next().setStyle({marginLeft:0});
	           	}
            }
        });
    });
</script>
