<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="form">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>                        
        <div class="row">
            <div class="span5">
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media-pdp') ?>
                </div>  
                <?php if($_product['product_video']):?>
                    <div class="video-play">
                        <a id="play-video" href="#"><span id="video-text">Play Video</span> <img src="<?php echo $this->getSkinUrl('img/ico-video-play.png')?>"/></a>
                    </div>
                <?php endif;?>                  
              
                <div class="quickviewpro_share">
                    <?php echo $this->getChildHtml('product_share') ?>
                </div>
            </div>
            <div itemscope itemtype="http://schema.org/Product" class="product-shop span4">
                <?php 
                    $now = date("Y-m-d");
                    $newsFrom= substr($_product->getData('news_from_date'),0,10);
                    $newsTo=  substr($_product->getData('news_to_date'),0,10);
                ?>
                <div class="product-name">
                    <h2 itemprop="name" class="productName"><?php if ($now>=$newsFrom && $now<=$newsTo):?><span id="newProduct">NEW! </span><?php endif;?><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php if($_product->getTypeID()=='giftcards'):echo $this->getChildHtml('product_type_data'); else:?>
	                <?php echo $this->getPriceHtml($_product) ?>
	                <?php echo $this->getChildHtml('extrahint') ?>
	                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
	                <?php echo $this->getChildHtml('alert_urls') ?>                             
	    
	                <?php echo $this->getChildHtml('info_tabs');
	          	endif; ?>                                                                    
            </div>
        </div>
        <div class="clearer"></div>
        <div class="row" id="product-add">  
        	<?php if($_product->getTypeID()!='giftcards'):?>          
            <div>&nbsp;</div>
            <div class="product-options span5">
                <div id="extra-links">
                    <a id="returns" href="#">Free Shipping & Returns</a>
                    <a href="#">Live Chat</a>
                    <a id="shipping" href="#">Shipping Rates</a>
                </div>
            </div>
            <?php endif;?>
            <div class="product-options-bottom span4">
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()):?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>                                                 
    
                <?php echo $this->getChildHtml('other');?>
    
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>  
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?> 
           </div>
        </div>     
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');                
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                
                if(!url){
                    url = jQuery('#product_addtocart_form').attr('action');
                }
                url = url.replace("checkout/cart","ajax/index");
                var data = jQuery('#product_addtocart_form').serialize();
                data += '&isAjax=1';      
                jQuery('#ajax_loader').show();
                jQuery.ajax({
                      url: url,
                      dataType: 'json',
                      type : 'post',
                      data: data,
                      success: function(data){
                        console.log(data);
                            jQuery('#ajax_loader').hide();
                            jQuery('.btn-primary').removeAttr("disabled");
                            if(jQuery('.top-nav-right #top-nav li')){
                                var search = jQuery('.top-nav-right #top-nav li:last').clone();
                                jQuery('.top-nav-right #top-nav li').remove();
                                jQuery('.top-nav-right #top-nav').append(data.toplink);
                                jQuery('.top-nav-right #top-nav').append(search);
                            }
                            open_overlay('cart-overlay', 'pdp-hider');
                            jQuery('#product-info').append('<div id="cart-image"><img height="60px" width="60px" src="' + data.product_image + '"/></div>' + 
                                '<div class="item-details"><h3>' + data.product_name + '</h3><p>$' + data.price + '</p><p class="item-qty">Qty: ' + data.qty + '</p></div><div class="item-btns"><a class="btn" href="/shop/index.php/checkout/cart/">Change</a><a class="btn" href="' + data.remove_url + '">Remove</a></div>')
                            jQuery('#cart-count').text(data.count);
                      }
                });

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
        function open_overlay(overlayId, hiderId)
        {
            var heightBody = document.getElementsByTagName('body')[0].clientHeight;
            jQuery('#' + hiderId).css('height', heightBody + 'px');
            jQuery('#' + hiderId).show();
            var scrollPos = null;
            if (document.documentElement && document.documentElement.scrollTop) { // Explorer 6 Strict
                scrollPos = {scrollTop:document.documentElement.scrollTop,scrollLeft:document.documentElement.scrollLeft};
            } else if (document.body) {// all other Explorers
                scrollPos = {scrollTop:document.body.scrollTop,scrollLeft:document.body.scrollLeft};
            }
            var topPos    = parseInt(0.1 * document.documentElement.clientHeight + scrollPos['scrollTop']);
    
            jQuery('#' + overlayId).css('top', topPos + 'px');
            if (window.outerWidth < parseInt(jQuery('#' + overlayId).css('width'))) {
                jQuery('#' + overlayId).css({'left': '0px', 'margin': '0 0 0 20px'});
            } else {
                jQuery('#' + overlayId).css({'left': '', 'margin': ''});
            }
            jQuery('#' + overlayId).show();         
        }
    //]]>
    </script>
    </div>
    <?php if($_product->getTypeID()!='giftcards'):?>
	    <div class="product-collateral">
	    <!--<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
	        <div class="box-collateral <?php echo "box-{$alias}"?>">
	            <?php if ($title = $this->getChildData($alias, 'title')):?>
	            <h2><?php echo $this->escapeHtml($title); ?></h2>
	            <?php endif;?>
	            <?php echo $html; ?>
	        </div>
	    <?php endforeach;?>-->
	    <?php echo $this->getChildHtml('upsell_products') ?>
	    <?php echo $this->getChildHtml('product_review') ?>
	    <?php echo $this->getChildHtml('product_additional_data') ?>
	    <?php echo $this->getChildHtml('tout');?>
	    </div>	
	<?php endif;?>
</div>
<div id="pdp-hider" class="quickviewpro-hider" style="display:none;background-color: rgb(136, 136, 136); height: 1381px;"></div>
<div id="returns-overlay" style="display:none" class="quickviewpro-popup">
    <a class="close-popap" href="javascript:void(0);"></a>
    <div class="custom-overlay overlay-returns">
        <?php echo $this->getChildHtml('returns_exchanges');?>
    </div>
</div>
<div id="shipping-overlay" style="display:none" class="quickviewpro-popup">
    <a class="close-popap" href="javascript:void(0);"></a>
    <div class="custom-overlay overlay-shipping">
        <?php echo $this->getChildHtml('shipping');?>
    </div>
</div>
<div id="video-overlay" style="display:none" class="quickviewpro-popup">
    <a class="close-popap" id="close-video" href="javascript:void(0);"></a>
    <div class="popup-header"><?php echo $_product->getName();?></div>
    <div id="video-main" class="main-popup custom-overlay">
        <div id="video-embed">
            <?php echo $_product['product_video'];?>
        </div>
    </div>  
</div>
<div id="cart-overlay" style="display:none;" class="quickviewpro-popup">
    <a class="close-popap" href="javascript:void(0);"></a>
    <div class="popup-header">Cart {<span id="cart-count"></span>}</div>
    <div class="main-popup custom-overlay overlay-cart">
        <div class="cart-top">
            <div class="cart-feature">
                <h1>Item added to your cart!</h1>
            </div>
            <div id="product-info" class="cart-top-item">
            </div>
        </div>
        <div class="cart-bottom">
            <div class="cart-btm-links">
                <div><a href="/sandal-straps.html">Shop Featured Straps</a></div>
                <div><a href="/sandal-accessories.html">Shop Featured Accessories</a></div>
            </div>
            <div class="cart-btm-btns">
                <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn btn-proceed-checkout btn-lrg btn-primary" onclick="window.location='/shop/index.php/checkout/onepage'"><span><span><?php echo $this->__('Checkout') ?></span></span></button>                  
                <button type="button" title="<?php echo $this->__('Keep Shopping') ?>" class="btn" onclick="setLocation('/shop/index.php/')"><span><span><?php echo $this->__('Keep Shopping') ?></span></span></button>
            </div>
        </div>
    </div>  
</div>