<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="form">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>                        
        <div class="row-fluid">
			<div class="span12">
				<div class="row-fluid">
					<div class="span7">
				        <div class="product-img-box">
				            <?php echo $this->getChildHtml('media-pdp') ?>
				        </div>	
				        <?php if($_product['product_video']):?>
					        <div class="video-play">
					        	<a id="play-video" href="#">Play Video <img src="<?php echo $this->getSkinUrl('img/ico-video-play.png')?>"/></a>
					        </div>
				        <?php endif;?>			        
                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        	<?php $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);?>
                        	<?php if(count($_attributes)):?>
                        		<?php foreach($_attributes as $_attribute): ?>
                        			<?php if($_attribute['attribute_code'] == 'base_color'): ?>
										<ul id="<?php echo $_attribute['attribute_id']?>" class="base-block">
											<li>Base Color</li>
											<?php foreach($_attribute['values'] as $_color):?>
												<li class="<?php echo $_color['label']?>" id="<?php echo $_color['value_index']?>" style="width:20px;background-color:<?php echo $_color['label']?>"></li>
											<?php endforeach;?>
										</ul>
                        			<?php endif;?>
                        		<?php endforeach;?>
                        	<?php endif;?>
                        <?php endif;?>
                        <div class="quickviewpro_share">
                            <?php echo $this->getChildHtml('product_share') ?>
                        </div>
			        </div>
			        <div class="product-shop span5">
			        	<?php 
				    		$now = date("Y-m-d");
							$newsFrom= substr($_product->getData('news_from_date'),0,10);
							$newsTo=  substr($_product->getData('news_to_date'),0,10);
				    	?>
			        	<div class="product-name">
			                <h2 class="productName"><?php if ($now>=$newsFrom && $now<=$newsTo):?><span id="newProduct">NEW! </span><?php endif;?><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
			            </div>
						
						<?php echo $this->getPriceHtml($_product) ?>
			            <?php echo $this->getChildHtml('extrahint') ?>
			            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
			            <?php echo $this->getChildHtml('alert_urls') ?>					            
			
						<?php echo $this->getChildHtml('info_tabs') ?>									            			          
			        </div>
				</div>
			</div>
	    </div>
	    <div class="clearer"></div>
	    <div class="row-fluid">
	    	<div class="span12">
	    		<div class="row-fluid">
	    		<?php if (!$this->hasOptions()):?>
	                <div class="add-to-box">
	                    <?php if($_product->isSaleable()): ?>
	                        <?php echo $this->getChildHtml('addtocart') ?>
	                    <?php endif; ?>
	                    <?php echo $this->getChildHtml('addto') ?>
	                </div>
	                <?php echo $this->getChildHtml('extra_buttons') ?>
	            <?php elseif (!$_product->isSaleable()): ?>
	                <div class="add-to-box">
	                    <?php echo $this->getChildHtml('addto') ?>
	                </div>
	            <?php endif; ?>													
	
	            <?php echo $this->getChildHtml('other');?>
	
	            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
	                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
	            <?php endif;?>	
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>   
        </div>
        </div>
	    </div>     
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
        	console.log(this);
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
    <div class="product-collateral">
	<!--<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
	<?php endforeach;?>-->
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_review') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
<div id="pdp-hider" class="quickviewpro-hider" style="display:none;background-color: rgb(136, 136, 136); height: 1381px;"></div>
<div id="returns-overlay" style="display:none" class="quickviewpro-popup">
	<a class="close-popap" href="javascript:void(0);"></a>
	<?php echo $this->getChildHtml('returns_exchanges');?>
</div>
<div id="shipping-overlay" style="display:none" class="quickviewpro-popup">
	<a class="close-popap" href="javascript:void(0);"></a>
	<?php echo $this->getChildHtml('shipping');?>
</div>
<div id="video-overlay" style="display:none" class="quickviewpro-popup">
	<a class="close-popap" id="close-video" href="javascript:void(0);"></a>
	<div class="popup-header"><?php echo $_product->getName();?></div>
	<div id="video-main" class="main-popup">
		<div id="video-embed">
			<?php echo $_product['product_video'];?>
		</div>
	</div>	
</div>
