<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
	<ol class="progtrckr" data-progtrckr-steps="4">
	    <li class="progtrckr-active"><p>Shopping Cart</p><span class="circle"></span></li><!--
	 --><li class="progtrckr-not"><p>Billing & Shipping</p><span class="circle"></span></li><!--
	 --><li class="progtrckr-not"><p>Confirm Order</p><span class="circle"></span></li><!--
	 --><li class="progtrckr-not" style="margin-right:0;"><p>Checkout Complete</p><span class="circle"></span></li>
	 <span class="line"></span>
	</ol>
    <div class="row">
		<div class="page-title span3" id="shopping-cart-page">
			<h1 style="margin-bottom:30px;"><?php echo $this->__('Shopping Cart') ?></h1>
		</div>
		<div class="span2" style="margin-top: 12px;">
			<?php if(!$this->hasError()): ?>
				<?php foreach ($this->getMethods('top_methods') as $method): ?>
					<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
						<?php echo $methodHtml; ?>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
		<div class="span2" style="margin-top: 12px;">
			<?php if($this->getContinueShoppingUrl()): ?>
				<button type="button" title="<?php echo $this->__('Keep Shopping') ?>" class="btn" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Keep Shopping') ?></span></span></button>
			<?php endif; ?>
		</div>
	</div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
        	<div class="cart-row">
        		<div class="row">
	        		<div class="span5">
	        			<h6>Product</h6>
	        		</div>
	        		<div class="span3">
	        			<h6>Quantity</h6>
	        		</div>
	        		<div class="span2">
	        			<h6>Price</h6>
	        		</div>
	        		<div class="span2">
	        			<h6>Total</h6>
	        		</div>
	        	</div>
        	</div>
        	<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
			<?php $session = Mage::getSingleton('checkout/session');
			foreach($session->getQuote()->getAllItems() as $_item): ?>
				<?php if(!$_item->getParentItemId()):?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endif;?>	
			<?php endforeach ?>
			<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
				<?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
				<?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?>
				<?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
				<?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?>
			<?php endif; ?>
        </fieldset>
        <button style="display:none;" id="updateShoppingCart" type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="btn btn-lrg shrink-wrap"><span><span><?php echo $this->__('Update Shopping Cart') ?></span></span></button>
    </form>
    <div class="container">
        <div class="row">
                <?php //echo $this->getChildHtml('crosssell') ?>
            <div class="span5">
				<?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
				<?php echo $this->getChildHtml('coupon') ?>
				<?php echo $this->getChildHtml('giftcards') ?>
            </div>
            <div class="span4 offset3 show-buttons">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <?php echo $methodHtml; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php endif; ?>
            </div>
            
            <!--<?php echo $this->getChildHtml('crosssell') ?>-->
            </div>
        </div>

    </div>
</div>