<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
// First, let's load some order details  
$order_id = Mage::getSingleton('checkout/session')->getLastRealOrderId(); 
$order_details = Mage::getModel('sales/order')->loadByIncrementId($order_id);
// Get shipping method
$shipping_method = $order_details->_data["shipping_description"];
// Get ship-to address information
$shipping_address_data = $order_details->getShippingAddress();
// Get payment information
$payment_method = $order_details->getPayment()->getMethodInstance()->getTitle();
// Get billing address information
$billing_address_data   = $order_details->getBillingAddress();

?>
<ol class="progtrckr" data-progtrckr-steps="4">
	    <li id="progress1" class="progtrckr-not"><p>Shopping Cart</p><span class="circle"></span></li><!--
	 --><li id="progress2" class="progtrckr-not"><p>Billing & Shipping</p><span class="circle"></span></li><!--
	 --><li id="progress3" class="progtrckr-not"><p>Confirm Order</p><span class="circle"></span></li><!--
	 --><li id="progress4" class="progtrckr-active" style="margin-right:0;"><p>Checkout Complete</p><span class="circle"></span></li>
	 <span class="line"></span>
	</ol>
<div class="page-title" id="order-complete" style="display:inline-block">
    <h1><?php echo $this->__('Order Complete') ?></h1>
</div>
<div class="buttons-set" style="display:inline-block; margin-left:50px;">
    <button type="button" class="btn btn-large" title="<?php echo $this->__('Keep Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><b><?php echo $this->__('Thanks for your order! Your Sseko order number is #%s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></b></p>
<?php  else :?>
    <p><b><?php echo $this->__('Thanks for your order! Your Sseko order number is #%s.', $this->escapeHtml($this->getOrderId())) ?></b></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>
<div class="cart-row" style="margin-top:50px;">
	<div class="row">
		<div class="span5">
			<h6>Product</h6>
		</div>
		<div class="span3">
			<h6>Quantity</h6>
		</div>
		<div class="span2">
			<h6>Price</h6>
		</div>
		<div class="span2">
			<h6>Total</h6>
		</div>
	</div>
</div>
<div class="cart-row confirm-row">
<?php
/*** Product Listing ***/
// Iterate through each product listing the name, the quantity ordered, and the item price
foreach ($order_details->getAllItems() as $item) { ?>
<div class="row" style="<?php if (!$item->getParentItemId()): ?>margin-bottom:10px; margin-top:10px;<?php endif;?>">
	<div class="span5">
		<?php if (!$item->getParentItemId()): ?>
			<p><b><?php echo $item->getName(); ?></b></p>
		<?php else: 
			if($item->getProductType() == 'configurable')
			{
				$productOptions = $item->getProductOptions(); 
			    if (isset($productOptions['attributes_info'])) :
				    foreach ($productOptions['attributes_info'] as $productOption) :
				        if($productOption['label'] == 'Size'):
							$sizeDisplay = 'Size '.$productOption['value'];
						endif;
						if($productOption['label'] == 'Base Color'):
							$baseDisplay = $productOption['value'].' Base';
						endif;
					endforeach;
			    endif;
		?>
			<p style="margin-left:20px;"><?php echo $baseDisplay.' - '.$sizeDisplay; ?></p>
		<?php 
			}	
			else{ 
		?>
			<p style="margin-left:20px;"><?php echo $item->getName(); ?></p>
		<?php } ?>
		<?php endif; ?>
		<p style="display:none"><?php echo $item->getSku(); ?></p>
	</div>
	<div class="span3">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo round($item->getQtyOrdered(), 0); ?></p>
		<?php endif; ?>
	</div>
	<div class="span2">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo Mage::helper("core")->currency($item->getPrice()); ?></p>
		<?php endif; ?>
	</div>
	<div class="span2">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo Mage::helper("core")->currency($item->getPrice() * $item->getQtyOrdered()); ?></p>
		<?php endif; ?>
	</div>
</div>
<?php } ?>
</div>
<?php
// Get the product id from the item (useful later for loading product attribute information)
$product_id = $item->getData('product_id');
/*** Billing amounts ***/
// These leverage the Magento core helper to format the numbers to currency 
?>
<div class="cart-row totals-row">
	<div class="row 1">
		<div class="span2 offset8">
			<h6>Subtotal</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($order_details->subtotal); ?></h6>
		</div>
	</div>
	<div class="row 2">
		<div class="span2 offset8">
			<h6>Shipping</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($order_details->shipping_amount); ?></h6>
		</div>
	</div>
	<div class="row 2">
		<div class="span2 offset8">
			<h6>Tax</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($order_details->tax_amount); ?></h6>
		</div>
	</div>
	<div class="row 3">
		<div class="span2 offset8">
			<h6>Total</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($order_details->grand_total); ?></h6>
			<p style="display:none;"><?php echo Mage::helper("core")->currency($order_details->discount_amount); ?></p>
		</div>
	</div>
</div>
<div class="row additional-confirm" style="padding:40px 0;">
	<div class="span3">
		<h2>Billing Info</h2>
		<?php 
		// Output the billing address information
		echo "<h6>" . $billing_address_data['firstname'];
		echo " " . $billing_address_data['lastname'];
		echo "</h6><h6>" . $billing_address_data['street'];
		echo "</h6><h6>" . $billing_address_data['city'];
		echo ", " . $billing_address_data['region'];
		echo " " . $billing_address_data['postcode'];
		echo "</h6><h6>" . $billing_address_data['country_id'];
		echo "</h6><h6>" . $billing_address_data['telephone']. "</h6>"; ?>
	</div>
	<div class="span3">
		<h2>Shipping Info</h2>
		<?php 
		// Output the ship-to address information
		echo "<h6>" . $shipping_address_data['firstname'];
		echo " " . $shipping_address_data['lastname'];
		echo "</h6><h6>" . $shipping_address_data['street'];
		echo "</h6><h6>" . $shipping_address_data['city'];
		echo ", " . $shipping_address_data['region'];
		echo " " . $shipping_address_data['postcode'];
		echo "</h6><h6>" . $shipping_address_data['country_id'];
		echo "</h6><h6>" . $shipping_address_data['telephone']. "</h6>";?>
	</div>
	<div class="span6" style="margin-top:10px;">
		<?php
		// Loads the CMS static block directly
		// Note: the identifier for the cms block in this example is success_faq - adjust to suite your cms
		echo $this->getLayout()->createBlock('cms/block')->setBlockId('confirm_page')->toHtml(); ?>
	</div>
</div>
<?php $subtotal = $order_details->subtotal;
	$discount = $order_details->discount_amount;
	$discountedTotal = $subtotal + $discount;
?>
<!--START AffiliateTraction CODE-->
<iframe src="https://ssekodesigns.affiliatetechnology.com/trackingcode_sale.php?mid=1&sec_id=M_14aL4kF3nX8iQ&sale=<?php echo $discountedTotal; ?>&orderId=<?php echo $this->getOrderId(); ?>&promo=<?php echo $order_details->getCouponCode(); ?>" height="1" width="1" frameborder=no border=0 scrolling=no></iframe>
<!-- END AffiliateTraction CODE -->

<?php $_customerId = Mage::getSingleton('customer/session')->getCustomerId(); $lastOrderId = Mage::getSingleton('checkout/session')->getLastOrderId(); $order = Mage::getSingleton('sales/order'); $order->load($lastOrderId); $_totalData =$order->getData(); $_sub = $_totalData['subtotal']; ?> <img src="https://shareasale.com/sale.cfm?tracking=<?php echo $this->getOrderId() ?>&amount=<?php echo $_sub ?>&transtype=sale&merchantID=41414" width="1" height="1">

<!-- Google Code for Sseko Purchase New Website Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1000760408;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "5W06COD5rwUQ2MiZ3QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1000760408/?value=0&amp;label=5W06COD5rwUQ2MiZ3QM&…"/>
</div>
</noscript>

<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6008459719262';
fb_param.value = '0.00';
fb_param.currency = 'USD';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6008459719262&amp;value=0&amp;currency=USD" /></noscript>

<script type="text/javascript">
	<?php $quoteId = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId())->getQuoteId();
		$quote = Mage::getModel('sales/quote')->load($quoteId);
		$method = $quote->getCheckoutMethod(true);
		if ($method == 'register' || $method == ''){?>
			var userStatus = 'Registered';
		<?php }
		elseif ($method == 'guest'){ ?>
			var userStatus = 'Guest';
	<?php }?>
	var _gaq = _gaq || [];
 	_gaq.push(['_setAccount', 'UA-9703291-1']);
	_gaq.push(['_trackPageview']);
	_gaq.push(['_setDomainName', 'ssekodesigns.com']);
	_gaq.push(['_setCustomVar', 1, 'User Status', userStatus, 1]);
	_gaq.push(['_addTrans',
  		'<?php echo $this->getOrderId()?>',                          // order ID - required 
  		'Sseko Designs',                  // affiliation or store name 
  		'<?php echo $order_details->grand_total; ?>',           // total - required
  		'<?php echo $order_details->tax_amount; ?>',                           // tax
  		'<?php echo $order_details->shipping_amount; ?>',                           // shipping
  		'<?php echo $billing_address_data['city']?>',                           // city
  		'<?php echo $billing_address_data['region']?>',                          // state or province
  		'<?php echo $billing_address_data['country_id']?>'                             // country
	]);
	<?php foreach ($order_details->getAllItems() as $item) { 
			$product=Mage::getModel('catalog/product')->load($item->getProductId());
	        $category_id=$product->getCategoryIds();
	        $category=Mage::getModel('catalog/category')->load($category_id[0]);    
	        $category_name=$category->getName();
		?>
		_gaq.push(['_addItem',
	  		'<?php echo $this->getOrderId()?>',                          // order ID - necessary to associate item with transaction 
	  		'<?php echo $item->getSku(); ?>',                          // SKU/code - required
	  		'<?php echo $item->getName(); ?>',       // product name 
	  		'<?php echo $category_name?>',                   // category or variation
	  		'<?php echo $item->getPrice()?>',                          // unit price - required 
	  		'<?php echo round($item->getQtyOrdered(), 0); ?>'                               // quantity - required
		]);
	<?php } ?>
	_gaq.push(['_trackTrans']);

 	(function() {
   		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 	})();
</script>
<script>
	<?php $quoteId = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId())->getQuoteId();
		$quote = Mage::getModel('sales/quote')->load($quoteId);
		$method = $quote->getCheckoutMethod(true);
		if ($method == 'register' || $method == ''){?>
			var userStatus = 'Registered';
		<?php }
		elseif ($method == 'guest'){ ?>
			var userStatus = 'Guest';
	<?php }?>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 	ga('create', 'UA-9703291-2', 'ssekodesigns.com');
 	ga('set', 'dimension1', userStatus); 
 	ga('send', 'pageview');

 	ga('require', 'ecommerce', 'ecommerce.js');

 	ga('ecommerce:addTransaction', {
		id: '<?php echo $this->getOrderId()?>', // Transaction ID - this is normally generated by your system.
	  	affiliation: 'Sseko Designs.', // Affiliation or store name
	  	revenue: '<?php echo $order_details->grand_total; ?>d', // Grand Total
	  	shipping: '<?php echo $order_details->shipping_amount; ?>' , // Shipping cost
	  	tax: '<?php echo $order_details->tax_amount; ?>' }); // Tax.
	<?php foreach ($order_details->getAllItems() as $item) { 
			$product=Mage::getModel('catalog/product')->load($item->getProductId());
	        $category_id=$product->getCategoryIds();
	        $category=Mage::getModel('catalog/category')->load($category_id[0]);    
	        $category_name=$category->getName();
		?>	
	 	ga('ecommerce:addItem', {
	  		id: '<?php echo $this->getOrderId()?>', // Transaction ID.
	  		sku: '<?php echo $item->getSku(); ?>', // SKU/code.
	  		name: '<?php echo $item->getName(); ?>', // Product name.
	  		category: '<?php echo $category_name?>', // Category or variation.
	  		price: '<?php echo $item->getPrice()?>', // Unit price.
	  		quantity: '<?php echo round($item->getQtyOrdered(), 0); ?>'}); // Quantity.
	<?php }?>
	ga('ecommerce:send');
</script>