<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<div class="cart-row" style="margin-top:10px;">
	<div class="row">
		<div class="span2" style="display:none">
			<h6><?php echo $this->__('Order #') ?></h6>
		</div>
		<div class="span1">
			<h6><?php echo $this->__('Date') ?></h6>
		</div>
		<div class="span2">
			<h6><?php echo $this->__('Ship To') ?></h6>
		</div>
		<div class="span2">
			<h6><?php echo $this->__('Total') ?></h6>
		</div>
		<div class="span2">
			<h6><?php echo $this->__('Status') ?></h6>
		</div>
		<div class="span2">
			&nbsp;
		</div>
	</div>
</div>
<div class="cart-row" style="margin-bottom:10px;">
	<?php $_odd = ''; ?>
	<?php foreach ($_orders as $_order): ?>
        <div class="row">
			<div class="span2" style="display:none">
				<p><?php echo $_order->getRealOrderId() ?></p>
			</div>
			<div class="span1">
				<p><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></p>
			</div>
			<div class="span2">
				<p><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></p>
			</div>
			<div class="span2">
				<p><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></p>
			</div>
			<div class="span2">
				<p><?php echo $_order->getStatusLabel() ?></p>
			</div>
			<div class="span2">
				<a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
			</div>
		</div>
	<?php endforeach; ?>
</div>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
