<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php $_order = $this->getOrder();?>
<div class="cart-row" style="margin-top:10px;">
	<div class="row">
		<div class="span4">
			<h6><?php echo $this->__('Product Name') ?></h6>
		</div>
		<div class="span2" style="display:none">
			<h6><?php echo $this->__('SKU') ?></h6>
		</div>
		<div class="span1">
			<h6><?php echo $this->__('Qty') ?></h6>
		</div>
		<div class="span2">
			<h6><?php echo $this->__('Price') ?></h6>
		</div>
		<div class="span2">
			<h6><?php echo $this->__('Total') ?></h6>
		</div>
	</div>
</div>
<div class="cart-row confirm-row">
<?php
/*** Product Listing ***/
// Iterate through each product listing the name, the quantity ordered, and the item price
$_items = $_order->getItemsCollection(); ?>
<?php $_index = 0; ?>
<?php $_count = $_items->count(); ?>
<?php foreach ($_items as $item): ?>
<div class="row" style="<?php if (!$item->getParentItemId()): ?>margin-bottom:10px; margin-top:10px;<?php endif;?>">
	<div class="span4">
		<?php if (!$item->getParentItemId()): ?>
			<p><b><?php echo $item->getName(); ?></b></p>
		<?php else: ?>
			<p style="margin-left:20px;"><?php echo $item->getName(); ?> x <?php echo round($item->getQtyOrdered(), 0); ?></p>
		<?php endif; ?>
	</div>
	<div class="span2" style="display:none">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo $item->getSku(); ?></p>
		<?php endif; ?>
	</div>
	<div class="span1">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo round($item->getQtyOrdered(), 0); ?></p>
		<?php endif; ?>
	</div>
	<div class="span2">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo Mage::helper("core")->currency($item->getPrice()); ?></p>
		<?php endif; ?>
	</div>
	<div class="span2">
		<?php if (!$item->getParentItemId()): ?>
			<p><?php echo Mage::helper("core")->currency($item->getPrice() * $item->getQtyOrdered()); ?></p>
		<?php endif; ?>
	</div>
</div>
<?php endforeach; ?>
</div>
<div class="cart-row totals-row">
	<div class="row 1">
		<div class="span2 offset5">
			<h6>Subtotal</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($_order->subtotal); ?></h6>
		</div>
	</div>
	<div class="row 2">
		<div class="span2 offset5">
			<h6>Shipping</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($_order->shipping_amount); ?></h6>
		</div>
	</div>
	<div class="row 2">
		<div class="span2 offset5">
			<h6>Tax</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($_order->tax_amount); ?></h6>
		</div>
	</div>
	<div class="row 3">
		<div class="span2 offset5">
			<h6>Total</h6>
		</div>
		<div class="span2">
			<h6><?php echo Mage::helper("core")->currency($_order->grand_total); ?></h6>
			<p style="display:none;"><?php echo Mage::helper("core")->currency($_order->discount_amount); ?></p>
		</div>
	</div>
</div>
<div class="row" style="margin-top:20px;">
	<div class="span3">
		<a href="/shop/sales/order/history/" alt="View all Orders"><< View all Orders</a>
	</div>
</div>
        <!--?php if ($_item->getParentItem()) continue; ?>

            <?php echo $this->getItemHtml($_item) ?>
            <!--<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
            <tr class="border<?php echo ($_index++ > $_count ?' last':'') ?>" id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
                <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
                <td class="gift-message-row" colspan="7">
                    <a href="#" title="<?php echo $this->__('Close') ?>" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>');" class="btn-close"><?php echo $this->__('Close') ?></a>
                    <dl class="gift-message">
                        <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?></dt>
                        <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?></dt>
                        <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
                    </dl>
                </td>
            </tr>
            <?php endif ?>-->
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
