<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head" style="margin-top:50px;">
        <h2 style="margin-bottom:20px;"><?php echo $this->__('Recent Orders') ?></h2>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
	<div class="cart-row" style="margin-top:10px;">
		<div class="row">
			<div class="span2" style="display:none">
				<h6><?php echo $this->__('Order #') ?></h6>
			</div>
			<div class="span1">
				<h6><?php echo $this->__('Date') ?></h6>
			</div>
			<div class="span2">
				<h6><?php echo $this->__('Ship To') ?></h6>
			</div>
			<div class="span2">
				<h6><?php echo $this->__('Total') ?></h6>
			</div>
			<div class="span2">
				<h6><?php echo $this->__('Status') ?></h6>
			</div>
			<div class="span2">
				&nbsp;
			</div>
		</div>
	</div>
    <div class="cart-row" style="margin-bottom:10px;">
    	<?php foreach ($_orders as $_order): ?>
			<div class="row">
				<div class="span2" style="display:none">
					<p><?php echo $_order->getRealOrderId() ?></p>
				</div>
				<div class="span1">
					<p><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></p>
				</div>
				<div class="span2">
					<p><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></p>
				</div>
				<div class="span2">
					<p><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></p>
				</div>
				<div class="span2">
					<p><?php echo $_order->getStatusLabel() ?></p>
				</div>
				<div class="span2">
					<a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
					<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
						<span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
					<?php endif ?>
				</div>
			</div>
		<?php endforeach; ?>
    </div>
    <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
