<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
/* @var $this Mage_Catalog_Block_Product_List_Toolbar */
?>

<?php if($this->getCollection()->getSize()): ?>
<div class="btn-group">					
    <label><?php echo $this->__('Sort')?></label>
    <select onchange="setLocation(this.value)">	            					
		<option value="<?php echo $this->getOrderUrl('entity_id', 'desc') ?>"<?php if($this->isOrderCurrent('entity_id') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>NEWEST</option>
		<option value="<?php echo $this->getOrderUrl('price', 'asc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>PRICE - LOW / HIGH</option>						
		<option value="<?php echo $this->getOrderUrl('price', 'desc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>PRICE - HIGH / LOW</option>
		<option value="<?php echo $this->getOrderUrl('ordered_qty', 'desc') ?>"<?php if($this->isOrderCurrent('ordered_qty') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>MOST POPULAR</option>						
    </select>
</div>        
<?php endif ?>