<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<?php $_items = $this->getItemCollection()->getItems();
	$all_products = array();
	foreach($_items as $_item):
		$cats = $_item->getCategoryIds();
		foreach ($cats as $category_id):
		    $_cat = Mage::getModel('catalog/category')->load($category_id) ;
			if(!isset($all_products[$_cat->getName()]))
		    {
		         $all_products[$_cat->getName()] = array();
		    }		
		    $all_products[$_cat->getName()][] = $_item;
		endforeach;
	endforeach;?>
<div class="box-collateral box-up-sell">	
	<?php foreach($all_products as $key => $category_product):?>
		<?php if($key == "Sandal Straps"):$key = "Straps";endif;?>
		<h2><?php echo $this->__('Add Recommended '.$key) ?></h2>
			<table class="table" id="upsell-product-table">
			<?php $this->resetItemsIterator(); ?>
	    	<?php for($_i=0;$_i<1;$_i++): ?>	    		
    			<tr>	    		
	    			<?php for($_j=0;$_j<3;$_j++): ?>
	    				<?php if(!empty($category_product[$_j])): ?>
		            		<td>	
		            			<?php $_link=$category_product[$_j];?>	
		            			<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
				                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
				                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
				                <div class="add-to-box">
				                	<?php echo $this->getChildHtml('addtocart') ?>
				                </div>	            					      
		            		</td>
	            		<?php endif; ?>
	            	<?php endfor;?>
	           	</tr>
	    	<?php endfor;?>
	    	</table>
	<?php endforeach;?>
</div>	
<?php endif ?>