<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Sign In') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    
        <div class="row">
            <div class="span5">
                <h2><?php echo $this->__('Returning Customers') ?></h2>
                <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form"  class="form-vertical">
                    <fieldset>
                            <div class="control-group row">
                                <label for="email" class="control-label span2"><?php echo $this->__('Email Address') ?></label>
                                <div class="controls span3">
                                    <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </div>
                            <div class="control-group row">    
                                <label for="pass" class="control-label span2" style="margin-bottom:0; margin-top:5px;line-height:18px;"><?php echo $this->__('Password') ?></label>
                                <div class="controls span3">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                </div>
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="forgot-left span2"><?php echo $this->__('Forgot Password?') ?></a>
                            </div>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                            <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>

                            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                                <input name="context" type="hidden" value="checkout" />
                            <?php endif; ?>
                        <div class="row">
                        	<div class="span3 offset2">
	                            <button type="submit" class="button btn btn-primary btn-lrg" title="<?php echo $this->__('Sign in & Checkout') ?>" name="send" id="send2"><?php echo $this->__('Sign in & Checkout') ?></button>
	                        </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span4 offset1">
				<h2><?php echo $this->__('Guest Checkout') ?></h2>
				<p style="margin-bottom:40px;"><?php echo $this->__('Continue checkout as a Sseko guest.<br /><br />If you’re new to our site, you may create an account during this checkout process.') ?></p>
				<button type="button" title="<?php echo $this->__('Checkout as our Guest') ?>" class="button btn btn-primary btn-lrg" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><?php echo $this->__('Checkout as our Guest') ?></button>
            </div>
        </div>


    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>