<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
<div class="my-wishlist">
    <div class="page-title title-buttons">
        <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
            <a href="<?php echo $this->helper('wishlist')->getRssUrl(); ?>" class="link-rss pull-right"><?php echo $this->__('RSS Feed') ?></a>
        <?php endif; ?>
        <h1><?php echo $this->__('My Wishlist') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->hasWishlistItems()): ?>
    <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post" class="form-horizontal">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="cart-row" style="margin-top:10px;">
				<div class="row">
					<div class="span3">
						<h6><?php echo $this->__('Product') ?></h6>
					</div>
					<div class="span4">
						<h6><?php echo $this->__('Comment') ?></h6>
					</div>
					<div class="span2">
						<h6><?php echo $this->__('Modify') ?></h6>
					</div>
				</div>
			</div>
            <div class="cart-row confirm-row">
                <?php foreach ($this->getWishlistItems() as $item): ?>
                	<div class="row">
	                    <?php
	                        $product = $item->getProduct();
	                        $isVisibleProduct = $product->isVisibleInSiteVisibility();
	                    ?>
	                    <div class="span3">
	                            <a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
	                            <h6 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h6>
	                            <?php echo $this->getPriceHtml($product) ?>
	                            <?php echo $this->getDetailsHtml($item) ?>
	                            <span style="display:none"><?php echo $this->getFormatedDate($item->getAddedAt()) ?></span>
	                    </div>
	                    <div class="span4">
	                    	<textarea style="height:100%;" name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>
	                    </div>
	                    <div class="span2">
	                        <?php if ($item->canHaveQty() && $isVisibleProduct): ?>
	                            <p style="margin-bottom:10px;"><input type="text" class="span2 qty" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" /></p>
	                        <?php endif; ?>
	                        <?php if ($product->isSaleable()): ?>
	                            <?php if ($isVisibleProduct): ?>
	                            	<button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php echo $item->getId(); ?>)" class="btn btn-lrg btn-primary"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                            <?php endif ?>
	                        <?php else: ?>
	                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                        <?php endif; ?>
	                        <!--<?php if ($isVisibleProduct): ?>
	                        	<p><a href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a></p>
	                        <?php endif ?>-->
	                        <p style="margin-top:20px;"><a href="<?php echo $this->getItemRemoveUrl($item) ?>" title="<?php echo $this->__('Remove Item') ?>" onclick="return confirmRemoveWishlistItem();"><?php echo $this->__('Remove Item')?></a></p>
						</div>
					</div>
                <?php endforeach ?>
            </div>
            <script type="text/javascript">decorateTable('wishlist-table')</script>
            <div class="row" style="margin-top:30px;">
                <div class="pull-right span4">
                    <button type="submit" style="width:100%; margin-bottom:10px;" onclick="this.name='save_and_share'" title="<?php echo $this->__('Share Wishlist') ?>" class="btn btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
                    <?php if($this->isSaleable()):?>
                        <button type="button" title="<?php echo $this->__('Add All to Cart') ?>" onclick="addAllWItemsToCart()" class="btn btn-lrg btn-primary"><span><span><?php echo $this->__('Add All to Cart') ?></span></span></button>
                    <?php endif;?>
                    <button type="submit" style="width:100%; margin-top:10px;" title="<?php echo $this->__('Update Wishlist') ?>" onclick="this.name='do'" class="btn btn-update"><span><span><?php echo $this->__('Update Wishlist') ?></span></span></button>
                </div>
            </div>
        </fieldset>
    </form>
    <?php else: ?>
        <p><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>
    <script type="text/javascript">
    //<![CDATA[
    function confirmRemoveWishlistItem() {
        return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
    }

    function focusComment(obj) {
        if( obj.value == '<?php echo $this->helper('wishlist')->defaultCommentString() ?>' ) {
            obj.value = '';
        } else if( obj.value == '' ) {
            obj.value = '<?php echo $this->helper('wishlist')->defaultCommentString() ?>';
        }
    }

    function addWItemToCart(itemId) {
        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
        url = url.gsub('%item%', itemId);
        var form = $('wishlist-view-form');
        if (form) {
            var input = form['qty[' + itemId + ']'];
            if (input) {
                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
                url += separator + input.name + '=' + encodeURIComponent(input.value);
            }
        }
        setLocation(url);
    }

    function addAllWItemsToCart() {
        var url = '<?php echo $this->getUrl('*/*/allcart') ?>';
        var separator = (url.indexOf('?') >= 0) ? '&' : '?';
        $$('#wishlist-view-form .qty').each(
            function (input, index) {
                url += separator + input.name + '=' + encodeURIComponent(input.value);
                separator = '&';
            }
        );
        setLocation(url);
    }
    //]]>
    </script>
</div>
<?php endif ?>