<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="form-add" id="review-form">
    <h2><?php echo $this->__('Write Your Review') ?> <span id="required">*REQUIRED</span></h2>
    <h4><?php echo $this->__('How would you rate this product?') ?> <em class="required">*</em></h4>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form" class="form">
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before')?>            
            <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <span id="input-message-box"></span>
                <div id="rating-star-form">
                	<div class="row">
                		<div class="span1 offset1">
                			<span class="star-head star-1"></span>
                		</div>
                		<div class="span1">
                			<span class="star-head star-2"></span>
                		</div>
                		<div class="span1">
                			<span class="star-head star-3"></span>
                		</div>
                		<div class="span1">
                			<span class="star-head star-4"></span>
                		</div>
                		<div class="span1">
                			<span class="star-head star-5"></span>
                		</div>
                	</div>
                	<?php foreach ($this->getRatings() as $_rating): ?>
	                	<div class="row">
	                		<div class="span1 star-title">
	                			<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>
	                		</div>
	                		<?php foreach ($_rating->getOptions() as $_option): ?>
	                            <div class="span1"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" /></div>
	                        <?php endforeach; ?>
	                	</div>
                	<?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <script type="text/javascript">decorateTable('product-review-table')</script>
            <?php endif; ?>
            <div class="row">
                <label for="nickname_field" class="required span2"><?php echo $this->__('Nickname') ?><em>*</em></label>
                <div class="controls span3">
                    <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
                </div>
			</div>
			<div class="row">
                <label for="summary_field" class="required span2"><?php echo $this->__('Review Title') ?><em>*</em></label>
                <div class="controls span3">
                    <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                </div>
			</div>
			<div class="row">
                <label for="review_field" class="required span2"><?php echo $this->__('Your Review') ?><em>*</em></label>
                <div class="controls span4">
                    <textarea name="detail" id="review_field" cols="5" rows="5" class="required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
                </div>
			</div>
            </fieldset>
            <div class="row">
            	<button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-primary btn-small span1 offset2"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;
    
                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');
    
                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }
    
                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
    <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
