<div class="sharethis">
    <ul class="share-block">
        <li class="share-title">
            <span>
                <?php echo $this->__('Share Sseko') ?>
            </span>
        </li>
        <li class="share-facebook">
            <a href="http://www.facebook.com/sharer/sharer.php?u=<?php echo $this->getPageUrl() ?>&t=<?php echo $this->getPageTitle() ?>" target="_blank" rel="nofollow">
                <img src="/wp-content/themes/ssekoDesigns/assets/img/ico-social-facebook.png"/>
            </a>
        </li>
        <li class="share-twitter">
            <a href="http://twitter.com/share?url=<?php echo $this->getPageUrl() ?>&text=<?php echo $this->getPageTitle() ?>" target="_blank" rel="nofollow">                
				<img src="/wp-content/themes/ssekoDesigns/assets/img/ico-social-twitter.png"/>
            </a>
        </li>
        <li class="share-googleplus">
            <a href="https://plus.google.com/share?url=<?php echo $this->getPageUrl() ?>&t=<?php echo $this->getPageTitle() ?>&gpsrc=frameless" target="_blank" rel="nofollow">
                <img src="/wp-content/themes/ssekoDesigns/assets/img/ico-social-google.png"/>
            </a>
        </li>        
        <li class="share-pinterest">
            <a href="http://pinterest.com/pin/create/button/?url=<?php echo $this->getPageUrl() ?>&media=<?php echo $this->getPageImg() ?>&description=<?php echo $this->getPageDesc() ?>"class="pin-it-button" target="_blank" rel="nofollow">
                <img src="/wp-content/themes/ssekoDesigns/assets/img/ico-social-pinterest.png"/>
            </a>
        </li>
    </ul>
</div>